spring.application.name=demo

# ===============================
# DATABASE CONFIG (RENDER POSTGRES)
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d6vms9ma2pns73am41r0-a.oregon-postgres.render.com:5432/kunal_v1g0?sslmode=require
spring.datasource.username=kunal_v1g0_user
spring.datasource.password=3DHlHqHQSbgYPUeP40b5N8rjk9pgEcWP

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# OPTIONAL (can remove warning)
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER (MANDATORY FOR RENDER)
# ===============================
server.port=${PORT:8080}
